#!/usr/bin/env zsh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
FONT_FACE="Hack Nerd Font"
# FONT_FACE="FantasqueSansMono Nerd Font"
DEFAULT_DISPLAY=1
DEFAULT_HEIGHT=35


##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

sketchybar	--bar \
                height=32 \
                blur_radius=0 \
                position=top \
                sticky=on \
                padding_left=23 \
                padding_right=23 \
                display=main \
                # color=0x6624273a

                # background.color=0xff24273a \
sketchybar	--default \
                updates=when_shown \
                background.padding_left=2 \
                background.padding_right=2 \
                background.corner_radius=5 \
                background.height=24 \
                icon.color=0xffffffff \
                icon.font="$FONT_FACE:Bold:17.0" \
                icon.padding_left=8 \
                icon.padding_right=7 \
                label.font="$FONT_FACE:Bold:12.0" \
                label.color=0xffcad3f5 \
                label.padding_left=0 \
                label.padding_right=7

sketchybar	--add	item current_space left \
            --set	current_space \
                        background.color=0xfff5a97f \
                        background.padding_right=5 \
                        icon.font="$FONT_FACE:Bold:13.0" \
                        icon.color=0xff24273a \
                        label.drawing=off \
                        script="$PLUGIN_DIR/current_space.sh" \
            --subscribe current_space front_app_switched mouse.clicked



python3 -c '
import os
import subprocess as sp
unk_icon=""
spaces_arr=[
    ["01_space_iterm", ""],
    ["02_space_notes", ""],
    ["03_space_radar", ""],
    ["04_space_calendar", ""],
    ["05_space_monitor", ""],
    ["06_space_docs", ""],
    ["07_space_mail", ""],
    ["08_space_chrome", ""],
    ["09_space_safari", ""],
    ["10_space_music", ""],
    ["11_space_code", "﬏"],
    ["12_space_xcode", ""],
    ["13_space_finder", ""],
    ["14_space_ptb", ""],
    ["15_space_webex", ""],
    ["16_space_logs", ""],
    ["17_space_unk17", unk_icon],
    ["18_space_unk18", unk_icon],
    ["19_space_slack", "聆" ],
    ["20_space_whatsapp", "甆"],
]
for space,icon in spaces_arr:
    # print(f"{space} -> {icon}")
    # space_ind = int(sp.check_output(f"", shell=True))
    # print(f""" cmd: $(yabai -m query --spaces --space | jq '"'"'map(select(.label=="{space}")).index'"'"'""")
    os.system(f"""space_ind=$(yabai -m query --spaces | jq '"'"'map(select(.label == "{space}"))[0].index'"'"');
        sketchybar -m --add space {space} left \
            --set {space} associated_display=$DEFAULT_DISPLAY \
                        associated_space=$space_ind \
                        icon={icon} \
                        click_script="yabai -m space --focus {space}" \
                        background.color=0xc0486646 \
                        icon.color=0xff8fa7ff \
                        icon.font="Hack Nerd Font:Bold:17.0" \
                        icon.padding_right=-3 \
                        icon.padding_left=5   \
                        background.drawing=on \
                        icon.highlight_color=0xffc053db \
            --subscribe {space} front_app_switched mouse.entered mouse.clicked mouse.exited""")
'

sketchybar -m --add bracket primary_spaces  01_space_iterm        \
                                            02_space_notes        \
                                            03_space_radar        \
                                            04_space_calendar     \
                                            05_space_monitor      \
                                            08_space_chrome       \
                                            09_space_safari       \
                                            10_space_music       \
                                            11_space_code        \
                                            12_space_xcode       \
                                            13_space_finder      \
                                            19_space_slack       \
                                            20_space_whatsapp    \
               --set primary_spaces background.color=0x5f24273a  \
                                    background.corner_radius=0   \
                                    icon.color=0xffd8dee9        \
                                    background.height=$DEFAULT_HEIGHT


# sketchybar 	--add item front_app left \
#             --set   front_app \
#                           background.color=0xffa6da95 \
#                           background.padding_left=0 \
#                           background.padding_right=0 \
#                           icon.y_offset=1 \
#                           icon.color=0xff24273a \
#                           label.drawing=no \
#                           script="$PLUGIN_DIR/front_app.sh" \
#           	--add item front_app.separator left \
#             --set   front_app.separator \
#                           icon= \
#                           background.padding_left=-3 \
#                           icon.y_offset=1 \
#                           icon.font="$FONT_FACE:Bold:20.0" \
#                           icon.color=0xffa6da95 \
#                           icon.padding_left=0 \
#                           icon.padding_right=0 \
#                           label.drawing=no \
#           --add item front_app.name left \
#           --set front_app.name \
#                     icon.drawing=off \
#                     label="Hello" \
#                     label.drawing=yes

# sketchybar  --add   bracket front_app_bracket \
#                     front_app \
#                     front_app.separator \
#                     front_app.name \
#             --subscribe	front_app front_app_switched \

# sketchybar	--add	item weather.moon q \
#             --set	weather.moon \
#                     	background.color=0x667dc4e4 \
#                     	background.padding_right=-7 \
#                     	icon.color=0xff181926 \
#                     	icon.font="$FONT_FACE:Bold:22.0" \
#                     	label.drawing=off \
#                     	script="$PLUGIN_DIR/moon.sh" \
#             --subscribe weather.moon mouse.clicked

# sketchybar	--add	item weather q \
#             --set	weather \
#                     	icon= \
#                     	icon.color=0xfff5bde6 \
#                         icon.font="$FONT_FACE:Bold:15.0" \
#                     	update_freq=1800 \
#                     	script="$PLUGIN_DIR/weather.sh" \
#             --subscribe weather system_woke

# SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
# sketchybar	--add	item spotify_playlist e \
#             --set	spotify_playlist \
#                         background.padding_left=-5 \
#                         background.color=0xaa24273a \
#                         icon= \
#                         icon.color=0xffc6a0f6 \
#                         icon.font="$FONT_FACE:Bold:19.0" \
#                         label.drawing=off \
#                         script="$PLUGIN_DIR/spotify_playlist.sh" \
#             --subscribe spotify_playlist mouse.clicked

# sketchybar  --add   event spotify_change $SPOTIFY_EVENT \
#             --add   item spotify e \
#             --set   spotify \
#                         icon= \
#                     	icon.font="$FONT_FACE:Bold:20.0" \
#                     	icon.y_offset=1 \
#                         label.drawing=off \
#                     	label.padding_left=2 \
#                         script="$PLUGIN_DIR/spotify.sh" \
#             --subscribe spotify spotify_change mouse.clicked

sketchybar  --add   item clock right \
            --set   clock \
                        icon= \
                        icon.y_offset=1 \
                        icon.color=0xffed8796 \
                        update_freq=10 \
                        script="$PLUGIN_DIR/clock.sh"

sketchybar	--add	item	volume right \
            --set volume \
                      icon.y_offset=1 \
                      icon.color=0xff8aadf4 \
                      label.drawing=no \
                      script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change

sketchybar  --add   item battery right \
            --set   battery \
                        icon.y_offset=1 \
                        update_freq=10 \
                        script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change volume_change
